### PR TITLE
Adding details command list with explanations

### PR DESCRIPTION
**Pull request by BNolet**
To avoid the creation of command related issues, I added a more detailed list of command with the explanations, giving a little more insight of how to use the skill.

### CODE REVIEW

**Comment by forslund** [comment]
Thanks!

We need to keep the example section as it is used in the Mycroft marketplace. Maybe you can restore it and keep the commands section you added as it currently is.

**Comment by BNolet** [comment]
Do you mean to say that the section should be called Examples rather than Commands?

**Comment by forslund** [comment]
I meant having both Examples and the Commands headings.

Examples with some general examples like it was before and then the detailed list of commands with the categories as you suggested.

**Comment by BNolet** [comment]
Should be good now :ok_hand:

**Comment by forslund** [comment]
Looks good. Merging

**Pull request merged**
