### PR TITLE
Refactor to not reschedule at every call

### PR DESCRIPTION
**Pull request by devs-mycroft**
- Allows the skill to load again
- Restructures the code to not reschedule the oauth check

### CODE REVIEW

**Comment by parthsuthar** [comment]
Question @forslund - 
1. Is there a Mopidy dependency to run this ?
2. Is this now available on home.mycroft now ?

**Comment by forslund** [comment]
1. This should be device agnostic. On the mark-1 we use `librespot` as a spotify node to handle playback. On the desktop it will work with the normal spotify client and should work with Spotify enabled devices.

2. Still not available, later today if all tests succeed.

**Comment by parthsuthar** [comment]
hey @forslund so I can see that the whitelisting has been committed and its available on home.mycroft. could you please clarify if I need to run mopidy on rpi to use this skill ?

**Comment by forslund** [comment]
A spotify connect node is needed to play locally on the pi. librespot/raspotify provides this. I am not sure mopidy does, but if it does it can be used.

**Comment by parthsuthar** [comment]
Got it. So I can install raspotify separately on RPi and this skill should
still work ?

**Pull request merged**
