### PR TITLE
Spotify logo in README.md

### PR DESCRIPTION
**Pull request by dvdvgt**
Switched to the spotify logo in the README as described in #97.

### CODE REVIEW

**Comment by forslund** [comment]
Thanks the logo looks good. Could you add it to the repo and use just the filename as url. See [AIY Voice-kit](https://github.com/andlo/picroft-google-aiy-voicekit-skill/blob/master/README.md) for an example.

**Comment by dvdvgt** [comment]
@forslund like this? Sorry for the messy commits. I had a merge conflict...

**Comment by forslund** [comment]
Looks good. I'll just squash your commits and merge. Thank you for helping out with this project, it's very much appreciated!

**Comment by dvdvgt** [comment]
Thanks. Your welcome! I'm glad to help :)

**Pull request merged**
