### PR TITLE
Provide more information on how to authenticate to Spotify

### PR DESCRIPTION
**Pull request by KathyReid**
* splits the authentication into two sections
* includes information about how to authenticate if you use Facebook to auth to Spotify

### CODE REVIEW

**Comment by joslruhr** [comment]
I followed link and am now unsure. Is this a problem or is there a solution. I don't use Facebook and received successful authorisation from Spotify but Mycroft on the Pi does not recognise it.

**Comment by joslruhr** [comment]
Ok sorry am new to this and have now read the comments properly. Thanks and I will try it out

**Comment by joslruhr** [comment]
Kathy I appreciate your time. My account screen in Spotify also Premium Family differs to yours. In place of the device password field I have change password which is a whole new ballgame. How did you get to the screen you captured. Do you have a setting that differs to mine. I am accessing Mycroft and Spotify from Germany. but even in english I still hit the wall.

**Comment by forslund** [comment]
Hi @joslruhr,

I'm not 100% sure of how family accounts work but I'll try to help.

What device are you using? a Mark-1?

What have you tried here? You've pressed the authorize button on home and entered your spotify username and password on https://home.mycroft.ai

Asking "what spotify devices are available" is the basic test. If it answers something like

"I couldn't find any Spot-ify devices.  This skill requires a Spot-ify Premium account to work properly." 

The authorization has worked and the skill can communicate with Spotify connect.

**Comment by joslruhr** [comment]
Hi Forslund. Thanks very much for your contact. I am using a Raspberry Pi 3. I installed Mycroft (but not Picroft). However it installed successfully and I have started to test it out. I saw your Spotify skill and decided to try that because I wanted to access my Spotify Premium (family) account from the Pi. Very easy installation using Mycroft. No problems with account authorisation in Spotify, and Mycroft is now registered as an app. However when I tried to access via Mycroft I got the device not authorised message. Kathy at Mycroft advised that there was a second level authorisation of device that I needed to do. That is where I came to a dead end. My spotify account screen gives me no device password field. Maybe there is something else that I need to trigger but cant work out what. My Spotify account is registered in Germany where I live but even switching to English gives me the same result.

Ok the message that Mycroft gives me is as you have written, but I still cant get further because of the need for device authorisation as per Kathy's post.

Any advice greafully received even it is pointing out something that I have done wrongly or havent done

**Comment by forslund** [comment]
Kathys instructions are only necessary IF you have a facebook based Spotify account. If you have a normal Spotify login that is not needed and your normal login should work.

If you have a git installation of Mycroft and the spotify skill the actual spotify player isn't installed on the device. (the skill is basically spotify connect (with some extra for the Mycroft Mark-1 to launch the spotify player) This info should probably be added to the readme as well.

For raspberry-pi I'd recommend installing raspotify or spotifyd.

**Pull request merged**
